version: '3.3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgres://db_ummf_user:n8VulyltfA0Ev2lkawD7AbLZYTVxWaCd@dpg-cp2dr8v79t8c73fs4ps0-a.oregon-postgres.render.com/db_ummf
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/clientApp